[package]
name = "rumqtt-alpn-sandbox"
version = "0.1.0"
authors = ["Legokichi Duckscallion <legokichi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.14"
env_logger = "0.6"
envy = "0.4"
failure = { version = "0.1", default-features = false }
futures-preview = { version = "0.3.0-alpha.17", features = ["async-await", "nightly"] }
log = "0.4"
log-derive = "0.3"
rumqtt = { git = "https://github.com/AtherEnergy/rumqtt", branch = "master" }
runtime = { version = "0.3.0-alpha.6", default-features = false }
runtime-tokio = "0.3.0-alpha.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = { git = "https://github.com/TeXitoi/structopt", branch = "master" }
tokio-fs = "0.1"
tokio-timer = "0.2"

[dev-dependencies]

