# Configure cross compilation for Android/Termux.
[target.aarch64-linux-android]
ar = "/home/legokichi/android-sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
linker = "/home/legokichi/android-sdk/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang"
rustflags = ["-Clink-arg=-fuse-ld=lld"]
