[package]
name = "jsonschema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonschema = { version = "0.17", default-features = false }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
valico = "4.0"
validator = { version = "0.15", features = ["derive"] }
anyhow = "1"